### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
### Support decision tasks, by providing an Environment reward wrapper, such as a Gymnasium-like RL environment. 
### The SampleRewardModel: 1. parses the Query and Response, 2. executes action, 3. returns reward.
reward_model: your_env_package.reward_model_wrapper.SampleRewardModel
reward_model_type: env
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: full
lora_rank: 8
lora_target: all

### dataset
dataset: identity,alpaca_en_demo
template: llama3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/full/ppo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
